<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        $products = [
            // Processors (CPU)
            [
                'category_id' => 1,
                'brand_id' => 1,
                'name' => 'Intel Core i9-14900K',
                'slug' => 'intel-core-i9-14900k',
                'images' => json_encode(['products/intel-i9-14900k.jpg']),
                'description' => 'The Intel Core i9-14900K represents the pinnacle of consumer desktop processor technology, built on the refined Intel 7 process technology. This flagship CPU features 24 cores (8 Performance-cores + 16 Efficient-cores) and 32 threads, delivering unprecedented performance for both gaming enthusiasts and content creators. With a base clock of 3.2 GHz and maximum boost clock reaching up to 6.0 GHz, this processor excels in single-threaded applications while maintaining exceptional multi-threaded performance. The 36MB Intel Smart Cache ensures rapid data access, while support for DDR5-5600 and DDR4-3200 memory provides flexibility for various system configurations. Advanced features include Intel Thermal Velocity Boost, Intel Turbo Boost Max Technology 3.0, and comprehensive overclocking capabilities. Whether you\'re rendering 4K videos, streaming while gaming, or running complex simulations, the i9-14900K delivers the raw computational power needed for the most demanding workloads. Compatible with LGA1700 socket motherboards and featuring integrated Intel UHD Graphics 770, this processor is the ultimate choice for high-performance computing.',
                'original_price' => 8500000,
                'final_price' => 8000000,
                'discount_percentage' => 6,
                'in_stock' => 1,
                'is_active' => 1,
                'is_featured' => 1,
                'on_sale' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'brand_id' => 2,
                'name' => 'AMD Ryzen 9 7950X',
                'slug' => 'amd-ryzen-9-7950x',
                'images' => json_encode(['products/amd-ryzen-9-7950x.jpg']),
                'description' => 'The AMD Ryzen 9 7950X stands as AMD\'s flagship desktop processor, engineered on the cutting-edge 5nm Zen 4 architecture. This powerhouse CPU features 16 cores and 32 threads, running at a base clock of 4.5 GHz with boost clocks reaching up to 5.7 GHz. Built for the AM5 platform, this processor supports next-generation DDR5 memory and PCIe 5.0 connectivity, ensuring future-proof performance for years to come. The 7950X excels in multi-threaded workloads such as 3D rendering, video encoding, scientific computing, and content creation, while delivering exceptional gaming performance. With 80MB of total cache (64MB L3 + 16MB L2), data-intensive applications run smoothly and efficiently. The processor features AMD\'s Precision Boost 2 technology for intelligent performance scaling and supports advanced overclocking through AMD Ryzen Master software. Integrated RDNA 2 graphics provide basic display output capabilities, while the innovative AMD EXPO technology ensures optimal memory performance. Whether you\'re a professional content creator, software developer, or enthusiast gamer, the Ryzen 9 7950X delivers uncompromising performance across all applications.',
                'original_price' => 9000000,
                'final_price' => 9000000,
                'discount_percentage' => 0,
                'in_stock' => 1,
                'is_active' => 1,
                'is_featured' => 1,
                'on_sale' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Graphics Cards (GPU)
            [
                'category_id' => 2,
                'brand_id' => 3,
                'name' => 'NVIDIA GeForce RTX 4080 SUPER',
                'slug' => 'nvidia-geforce-rtx-4080-super',
                'images' => json_encode(['products/rtx-4080-super.jpg']),
                'description' => 'The NVIDIA GeForce RTX 4080 SUPER redefines high-end gaming and creative workflows with its revolutionary Ada Lovelace architecture built on the advanced TSMC 4N process. Featuring 10,240 CUDA cores, 320 Tensor cores, and 80 RT cores, this graphics powerhouse delivers exceptional 4K gaming performance and accelerated AI workloads. With 16GB of ultra-fast GDDR6X memory running at 23 Gbps across a 256-bit memory interface, the RTX 4080 SUPER provides ample bandwidth for high-resolution textures and complex scenes. Experience gaming like never before with 3rd generation RT cores that deliver up to 2.8x the ray tracing performance of previous generation cards, enabling realistic lighting, reflections, and shadows in supported games. The 4th generation Tensor cores accelerate AI-powered features like DLSS 3 Frame Generation, which can more than double frame rates while maintaining exceptional image quality. Content creators benefit from dedicated AV1 encoding, supporting efficient streaming and video production workflows. Advanced features include NVIDIA Reflex for reduced input latency, NVIDIA Broadcast for AI-enhanced streaming, and NVIDIA Studio for accelerated creative applications. The card supports PCIe 4.0, DisplayPort 1.4a, and HDMI 2.1 connectivity, making it compatible with the latest high-refresh-rate 4K monitors and VR headsets.',
                'original_price' => 18000000,
                'final_price' => 17000000,
                'discount_percentage' => 6,
                'in_stock' => 1,
                'is_active' => 1,
                'is_featured' => 1,
                'on_sale' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'brand_id' => 2,
                'name' => 'AMD Radeon RX 7800 XT',
                'slug' => 'amd-radeon-rx-7800-xt',
                'images' => json_encode(['products/rx-7800-xt.jpg']),
                'description' => 'The AMD Radeon RX 7800 XT represents exceptional value in high-performance gaming, built on the groundbreaking RDNA 3 architecture using advanced chiplet design and 5nm process technology. This graphics card features 3,840 stream processors and 16GB of high-speed GDDR6 memory, delivering outstanding 1440p gaming performance and solid 4K capabilities. The innovative chiplet architecture separates compute and memory cache dies, enabling AMD to optimize each component for maximum efficiency and performance. With 64MB of AMD Infinity Cache, the RX 7800 XT significantly reduces memory latency and improves bandwidth utilization, resulting in smoother gameplay and faster loading times. Hardware-accelerated ray tracing brings realistic lighting and reflections to your favorite games, while AMD FidelityFX Super Resolution (FSR) technology boosts frame rates without compromising visual quality. The card supports the latest connectivity standards including DisplayPort 2.1 and HDMI 2.1, enabling support for 8K displays and high-refresh-rate 4K gaming. AMD Smart Access Memory and Resizable BAR support unlock additional performance when paired with compatible AMD processors. Content creators benefit from dedicated AV1 encode/decode capabilities, dual media engines, and support for professional applications through AMD Radeon Pro Software. Whether gaming at 1440p high settings or diving into content creation, the RX 7800 XT delivers exceptional performance per dollar.',
                'original_price' => 12000000,
                'final_price' => 12000000,
                'discount_percentage' => 0,
                'in_stock' => 1,
                'is_active' => 1,
                'is_featured' => 0,
                'on_sale' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Motherboards
            [
                'category_id' => 3,
                'brand_id' => 4,
                'name' => 'ASUS ROG STRIX Z790-E',
                'slug' => 'asus-rog-strix-z790-e',
                'images' => json_encode(['products/asus-z790-e.jpg']),
                'description' => 'The ASUS ROG STRIX Z790-E GAMING WIFI represents the pinnacle of gaming motherboard engineering, designed to unleash the full potential of 13th and 12th generation Intel Core processors. Built on the robust LGA1700 socket with the Intel Z790 chipset, this ATX motherboard delivers exceptional overclocking capabilities and comprehensive connectivity options. The advanced power delivery system features 18+1 power stages with ProCool II power connectors, ensuring stable power delivery even under extreme overclocking conditions. Premium components including Japanese capacitors, 15K black metallic capacitors, and microfine alloy chokes guarantee long-term reliability and performance. The motherboard supports up to 128GB of DDR5 memory with speeds up to DDR5-7200+ (OC), enabling lightning-fast system responsiveness and future-proof performance. Four PCIe 5.0 x16 slots with SafeSlot Core+ reinforcement support multiple high-end graphics cards, while five M.2 slots with individual heatsinks accommodate the fastest NVMe SSDs available. Comprehensive connectivity includes WiFi 6E, Bluetooth 5.3, 2.5G Ethernet, USB 3.2 Gen 2x2 Type-C, and Thunderbolt 4 support. The SupremeFX 7.1 audio subsystem with ESS Sabre9018Q2C DAC delivers audiophile-grade sound quality. Advanced features include AI Overclocking, Aura Sync RGB lighting, BIOS FlashBack, and comprehensive fan controls. Whether you\'re building a high-end gaming rig or a professional workstation, the ROG STRIX Z790-E provides the foundation for exceptional performance.',
                'original_price' => 7500000,
                'final_price' => 7200000,
                'discount_percentage' => 4,
                'in_stock' => 1,
                'is_active' => 1,
                'is_featured' => 1,
                'on_sale' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'brand_id' => 5,
                'name' => 'MSI MAG B650 TOMAHAWK',
                'slug' => 'msi-mag-b650-tomahawk',
                'images' => json_encode(['products/msi-b650-tomahawk.jpg']),
                'description' => 'The MSI MAG B650 TOMAHAWK WIFI delivers exceptional value and performance for AMD Ryzen 7000 series processors, featuring the advanced AM5 socket and B650 chipset. This ATX motherboard combines robust build quality with comprehensive features, making it ideal for gamers and enthusiasts seeking reliable performance without premium pricing. The enhanced power delivery system utilizes a 14+2+1 phases design with 60A Smart Power Stage components, ensuring stable power delivery for high-performance processors under demanding workloads. Premium components including solid capacitors and dark chokes guarantee long-term reliability and consistent performance. Support for DDR5 memory up to 6000+ MHz (OC) with four DIMM slots accommodating up to 128GB provides ample room for future upgrades. The motherboard features four PCIe slots including one PCIe 5.0 x16 slot with Steel Armor reinforcement for graphics cards, plus additional PCIe 4.0 and 3.0 slots for expansion cards. Four M.2 slots with individual thermal solutions support the latest NVMe SSDs, while multiple SATA 6Gb/s ports provide extensive storage connectivity. Comprehensive I/O includes WiFi 6E, Bluetooth 5.3, 2.5G LAN, USB 3.2 Gen 2 Type-A and Type-C ports, and high-quality audio with Audio Boost technology. MSI Center software provides intuitive system monitoring, overclocking, and RGB lighting control through Mystic Light Sync. The TOMAHAWK series\' renowned reliability and performance heritage makes this motherboard an excellent foundation for both gaming and productivity-focused builds.',
                'original_price' => 3500000,
                'final_price' => 3500000,
                'discount_percentage' => 0,
                'in_stock' => 1,
                'is_active' => 1,
                'is_featured' => 0,
                'on_sale' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Memory (RAM)
            [
                'category_id' => 4,
                'brand_id' => 6,
                'name' => 'Corsair Vengeance LPX 32GB DDR4-3200',
                'slug' => 'corsair-vengeance-lpx-32gb-ddr4-3200',
                'images' => json_encode(['products/corsair-vengeance-lpx-32gb.jpg']),
                'description' => 'The Corsair Vengeance LPX 32GB DDR4-3200 memory kit represents the perfect balance of performance, reliability, and value for high-performance computing systems. This dual-channel kit consists of two 16GB modules engineered with carefully screened memory ICs and optimized for wide compatibility across Intel and AMD platforms. Operating at DDR4-3200 with CL16-18-18-36 timings, this memory delivers substantial performance improvements over standard DDR4-2133 memory, enhancing system responsiveness in gaming, content creation, and productivity applications. The low-profile design with distinctive heat spreader not only provides effective thermal management but also ensures compatibility with large CPU coolers and compact chassis builds. Each module is built using high-quality PCB and rigorously tested for stability and performance using advanced testing methodologies. The memory features XMP 2.0 profiles for easy overclocking and optimization, allowing users to achieve rated speeds with simple BIOS configuration. Corsair\'s legendary build quality ensures reliable operation under extended gaming sessions and demanding workloads. The 32GB capacity provides ample headroom for modern applications, virtual machines, content creation software, and future-proofing against increasing memory requirements. Whether building a gaming rig, workstation, or general-purpose system, the Vengeance LPX delivers consistent performance with the reliability Corsair is known for. Lifetime warranty and extensive compatibility testing across major motherboard manufacturers ensure peace of mind and hassle-free installation.',
                'original_price' => 2200000,
                'final_price' => 2000000,
                'discount_percentage' => 9,
                'in_stock' => 1,
                'is_active' => 1,
                'is_featured' => 0,
                'on_sale' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 4,
                'brand_id' => 6,
                'name' => 'Corsair Dominator Platinum RGB 64GB DDR5-5600',
                'slug' => 'corsair-dominator-platinum-rgb-64gb-ddr5-5600',
                'images' => json_encode(['products/corsair-dominator-64gb-ddr5.jpg']),
                'description' => 'The Corsair Dominator Platinum RGB 64GB DDR5-5600 represents the absolute pinnacle of memory technology, engineered for enthusiasts and professionals who demand uncompromising performance and premium aesthetics. This flagship memory kit features two 32GB modules utilizing cutting-edge DDR5 technology, delivering unprecedented bandwidth and efficiency compared to previous DDR4 generations. Operating at DDR5-5600 with optimized timings, this memory provides massive performance improvements in memory-intensive applications including 3D rendering, video editing, scientific computing, and next-generation gaming. The iconic Dominator heat spreader design features precision-machined aluminum construction with distinctive styling that has become synonymous with premium performance memory. Advanced thermal management includes integrated thermal sensors and efficient heat dissipation, ensuring optimal operating temperatures under sustained high-performance workloads. Each module incorporates individually controllable RGB lighting zones with Corsair iCUE software integration, enabling synchronized lighting effects across compatible Corsair components. The 64GB capacity provides extensive headroom for professional workloads, extensive multitasking, virtual machines, and future application requirements. Hand-sorted, tightly-screened memory ICs undergo rigorous testing and validation to ensure exceptional overclocking potential and long-term stability. Intel XMP 3.0 and AMD EXPO profiles enable easy optimization for maximum performance on compatible platforms. Premium features include enhanced PCB design, gold-plated contacts, and comprehensive compatibility testing across major motherboard manufacturers. Whether powering a high-end workstation, enthusiast gaming system, or professional content creation rig, the Dominator Platinum RGB delivers unmatched performance with the legendary Corsair reliability.',
                'original_price' => 8000000,
                'final_price' => 8000000,
                'discount_percentage' => 0,
                'in_stock' => 1,
                'is_active' => 1,
                'is_featured' => 1,
                'on_sale' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Storage
            [
                'category_id' => 5,
                'brand_id' => 8,
                'name' => 'Samsung 980 PRO 2TB NVMe SSD',
                'slug' => 'samsung-980-pro-2tb-nvme-ssd',
                'images' => json_encode(['products/samsung-980-pro-2tb.jpg']),
                'description' => 'The Samsung 980 PRO 2TB NVMe SSD represents the cutting edge of consumer storage technology, engineered to deliver flagship performance for gaming, content creation, and professional applications. Built using Samsung\'s advanced V-NAND 3-bit MLC technology and proprietary Elpis controller, this PCIe 4.0 NVMe SSD achieves exceptional sequential read speeds up to 7,000 MB/s and write speeds up to 6,900 MB/s. These performance levels dramatically reduce loading times in games, accelerate file transfers, and enhance overall system responsiveness compared to traditional SATA SSDs and mechanical drives. The M.2 2280 form factor ensures compatibility with modern motherboards and laptops, while the single-sided design accommodates space-constrained installations. Advanced thermal management features include Dynamic Thermal Guard technology that monitors and maintains optimal operating temperatures to prevent performance throttling during sustained workloads. The drive utilizes Samsung\'s proven reliability engineering with comprehensive error correction, wear leveling, and over-provisioning to ensure long-term data integrity and drive longevity. With 2TB capacity, users can store extensive game libraries, large media files, and professional applications without storage constraints. The 980 PRO includes Samsung Magician software for drive monitoring, firmware updates, performance optimization, and secure data migration from existing drives. Whether building a high-performance gaming system, professional workstation, or content creation rig, the Samsung 980 PRO delivers the storage performance needed to eliminate bottlenecks and maximize system potential. Five-year limited warranty and Samsung\'s industry-leading support provide confidence in long-term reliability.',
                'original_price' => 4500000,
                'final_price' => 4200000,
                'discount_percentage' => 7,
                'in_stock' => 1,
                'is_active' => 1,
                'is_featured' => 1,
                'on_sale' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 5,
                'brand_id' => 9,
                'name' => 'Western Digital Black SN850X 1TB',
                'slug' => 'wd-black-sn850x-1tb',
                'images' => json_encode(['products/wd-black-sn850x-1tb.jpg']),
                'description' => 'The Western Digital Black SN850X 1TB represents gaming-focused storage excellence, specifically engineered to meet the demanding requirements of modern gaming and content creation. This PCIe Gen4 NVMe SSD utilizes advanced 3D NAND technology and Western Digital\'s proprietary controller to deliver exceptional sequential read speeds up to 7,300 MB/s, ensuring lightning-fast game loading times and seamless texture streaming. The drive excels in random read/write performance with up to 1,200K/1,100K IOPS respectively, providing responsive system performance for multitasking scenarios and complex gaming environments. The included low-profile heatsink effectively dissipates heat during intensive workloads, maintaining consistent performance without thermal throttling during extended gaming sessions or content creation tasks. Game Mode 2.0 technology optimizes the drive specifically for gaming workloads, reducing latency and improving responsiveness in supported games and applications. The M.2 2280 form factor ensures broad compatibility with gaming laptops, desktops, and PlayStation 5 consoles for storage expansion. Advanced endurance rating and comprehensive error correction ensure reliable operation under demanding gaming and creative workloads. WD_BLACK Dashboard software provides real-time monitoring, performance optimization, and gaming mode controls for maximum customization. The drive features predictive loading technology that anticipates and pre-loads frequently accessed game assets, further reducing loading times and improving gaming experience. Whether building a high-performance gaming PC, upgrading a console, or enhancing a content creation workstation, the SN850X delivers the storage performance needed for competitive gaming and professional applications. Five-year limited warranty and Western Digital\'s gaming-focused support ensure reliable operation for years of intensive use.',
                'original_price' => 2800000,
                'final_price' => 2800000,
                'discount_percentage' => 0,
                'in_stock' => 1,
                'is_active' => 1,
                'is_featured' => 0,
                'on_sale' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Power Supplies
            [
                'category_id' => 6,
                'brand_id' => 6,
                'name' => 'Corsair RM850x 850W 80+ Gold',
                'slug' => 'corsair-rm850x-850w-80-plus-gold',
                'images' => json_encode(['products/corsair-rm850x.jpg']),
                'description' => 'The Corsair RM850x 850W 80+ Gold power supply exemplifies premium power delivery engineering, designed to provide rock-solid stability and efficiency for high-performance computing systems. This fully modular ATX power supply utilizes high-quality Japanese capacitors and a thermally controlled 135mm rifle bearing fan that operates in zero RPM mode at low loads, ensuring virtually silent operation during typical computing tasks. The 80+ Gold certification guarantees exceptional efficiency exceeding 90% at typical loads, reducing energy consumption and heat generation while lowering electricity costs over the power supply\'s lifespan. Advanced LLC resonant converter topology and dedicated +12V rails provide clean, stable power delivery with excellent voltage regulation under varying load conditions. The fully modular cable design allows users to connect only necessary cables, improving airflow and system aesthetics while simplifying cable management in modern chassis. Premium sleeved cables included with the unit feature flat ribbon construction that enhances airflow and visual appeal. Comprehensive protection features include over-voltage, under-voltage, over-current, over-power, short-circuit, and over-temperature protection, safeguarding valuable system components from power-related damage. The power supply meets all current safety standards including 80+ Gold efficiency requirements and features active PFC for improved power factor correction. Ten-year warranty demonstrates Corsair\'s confidence in the RM850x\'s long-term reliability and performance. Whether powering a high-end gaming system with multiple graphics cards or a professional workstation with demanding components, the RM850x delivers the clean, reliable power needed for optimal system performance and longevity.',
                'original_price' => 2500000,
                'final_price' => 2300000,
                'discount_percentage' => 8,
                'in_stock' => 1,
                'is_active' => 1,
                'is_featured' => 0,
                'on_sale' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // PC Cases
            [
                'category_id' => 7,
                'brand_id' => 6,
                'name' => 'Corsair 4000D Airflow',
                'slug' => 'corsair-4000d-airflow',
                'images' => json_encode(['products/corsair-4000d-airflow.jpg']),
                'description' => 'The Corsair 4000D Airflow represents the perfect fusion of thermal performance, build quality, and user-friendly design in a mid-tower chassis. Engineered with enthusiast builders in mind, this case prioritizes airflow optimization through its distinctive mesh front panel that maximizes air intake while maintaining dust filtration capabilities. The spacious interior accommodates high-end components including graphics cards up to 360mm in length, CPU coolers up to 170mm in height, and multiple storage devices with dedicated mounting points. Two pre-installed Corsair AirGuide 120mm PWM fans provide immediate cooling performance, with mounting points for up to ten total fans or multiple radiator configurations including 360mm radiators in both front and top positions. The innovative cable management system features dual-chamber design with dedicated PSU shroud, multiple cable routing grommets, and ample space behind the motherboard tray for clean cable routing. Tempered glass side panel showcases internal components while providing easy access for maintenance and upgrades. The case features removable dust filters on all intake points, simplifying maintenance and keeping internal components clean. Modern connectivity includes USB 3.1 Gen 1 Type-A and Type-C ports conveniently located on the top panel. Tool-free installation features include thumb screws for side panels and expansion slots, while the PSU mounting system accommodates both ATX and SFX power supplies. Premium build quality utilizing steel construction with powder-coated finish ensures durability and professional appearance. Whether building a high-performance gaming system, workstation, or custom loop cooling configuration, the 4000D Airflow provides the foundation for exceptional thermal performance and easy building experience.',
                'original_price' => 1800000,
                'final_price' => 1800000,
                'discount_percentage' => 0,
                'in_stock' => 1,
                'is_active' => 1,
                'is_featured' => 0,
                'on_sale' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Cooling
            [
                'category_id' => 8,
                'brand_id' => 6,
                'name' => 'Corsair H100i RGB ELITE',
                'slug' => 'corsair-h100i-rgb-elite',
                'images' => json_encode(['products/corsair-h100i-rgb-elite.jpg']),
                'description' => 'The Corsair H100i RGB ELITE represents premium all-in-one liquid cooling technology, engineered to deliver exceptional thermal performance while adding stunning visual appeal to any build. This 240mm AIO cooler features a redesigned pump head with ultra-bright RGB lighting and Corsair\'s latest generation cooling technology for superior heat dissipation. The split-flow copper cold plate maximizes surface area contact with CPU heat spreaders, while the efficient pump design ensures optimal coolant circulation with minimal noise generation. Two Corsair ML120 RGB ELITE PWM fans provide exceptional static pressure and airflow performance, featuring magnetic levitation bearing technology for virtually silent operation and extended lifespan. The radiator utilizes high-density fin construction with optimized tube routing for maximum heat transfer efficiency. RGB lighting integration includes both pump head and fan lighting synchronized through Corsair iCUE software, enabling complex lighting effects, temperature-based color changes, and ecosystem synchronization with other compatible components. Advanced pump design features PWM control for variable speed operation based on system temperatures, balancing cooling performance with acoustic levels. The cooler supports all modern CPU sockets including Intel LGA1700, LGA1200, and AMD AM4/AM5 platforms with comprehensive mounting hardware included. Zero RPM mode operation allows fans to stop completely at low temperatures, ensuring silent operation during light computing tasks. Pre-applied thermal compound and detailed installation instructions simplify the installation process for builders of all experience levels. Whether cooling high-end processors under extreme overclocking conditions or maintaining optimal temperatures in demanding applications, the H100i RGB ELITE delivers professional-grade cooling performance with the visual impact that defines modern PC builds. Six-year warranty and Corsair\'s renowned customer support provide confidence in long-term reliability and performance.',
                'original_price' => 2200000,
                'final_price' => 2000000,
                'discount_percentage' => 9,
                'in_stock' => 1,
                'is_active' => 1,
                'is_featured' => 1,
                'on_sale' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('products')->insert($products);
    }
}
